# -*- coding: utf-8 -*-
"""
/***************************************************************************
 erosion_dilatation
                                 A QGIS plugin
 Ce plugin permet de réaliser les traitements spatiaux d'érosion dilatation.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-31
        copyright            : (C) 2020 by Olivier Pompier
        email                : ol.pompier@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load erosion_dilatation class from file erosion_dilatation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .erosion_dilatation import erosion_dilatation
    return erosion_dilatation(iface)
